import { useMemo, useState } from "react";
import {
  Activity, BellRing, Boxes, Check, ChevronDown, CircleHelp, CloudDownload, Cpu, Download, ExternalLink, FileCode2, Gauge, LoaderCircle, MonitorPlay, Play, Plus, RefreshCw, Search, Server, SlidersHorizontal, Sparkles, Users, Wifi,
} from "lucide-react";
import { AppShell, CodeBlock, CopyButton, PageIntro, SectionCard, AccentTag, copyText } from "@/components/AppShell";
import { classNames, getLegacyStyle, mixColors, soundRecords, stripLegacy, toBungee, toSpigot } from "@/lib/toolkit";

const fieldClass = "h-10 w-full rounded-lg border border-white/[0.09] bg-black/20 px-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-emerald-300/45 focus:ring-2 focus:ring-emerald-300/10";
const selectClass = `${fieldClass} appearance-none`;
const textareaClass = "min-h-28 w-full resize-y rounded-lg border border-white/[0.09] bg-black/20 px-3 py-2.5 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-emerald-300/45 focus:ring-2 focus:ring-emerald-300/10";
const labelClass = "mb-2 block text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500";

const Toggle = ({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) => <button onClick={onChange} className={classNames("inline-flex items-center gap-2 rounded-lg border px-2.5 py-1.5 text-xs font-semibold transition active:scale-[.97]", checked ? "border-emerald-300/25 bg-emerald-300/10 text-emerald-200" : "border-white/[0.08] bg-white/[0.03] text-slate-500 hover:text-slate-300")}><span className={classNames("size-1.5 rounded-full", checked ? "bg-emerald-300 shadow-[0_0_7px_#55ff55]" : "bg-slate-600")} />{label}</button>;

export function ColorGenerator() {
  const [text, setText] = useState("BlockForge");
  const [start, setStart] = useState("#55FF55");
  const [end, setEnd] = useState("#55FFFF");
  const [isGradient, setGradient] = useState(true);
  const [bold, setBold] = useState(true);
  const [italic, setItalic] = useState(false);
  const legacy = getLegacyStyle(text);
  const cleanText = stripLegacy(text) || "Your text";
  const previewStyle = isGradient ? { backgroundImage: `linear-gradient(90deg, ${start}, ${end})`, backgroundClip: "text", WebkitBackgroundClip: "text", color: "transparent" } : { color: legacy.color };
  const json = JSON.stringify({ text: cleanText, color: isGradient ? start.replace("#", "") : legacy.color.replace("#", ""), bold, italic }, null, 2);
  const outputs = [
    ["JSON Text Component", json],
    ["Bukkit / Spigot", `${toSpigot(start)}${cleanText}`],
    ["BungeeCord", `${toBungee(start)}${cleanText}`],
    ["MiniMessage", isGradient ? `<gradient:${start}:${end}>${cleanText}</gradient>` : `<color:${start}>${cleanText}</color>`],
    ["Legacy", `&a${cleanText}`],
  ];
  return <AppShell><PageIntro eyebrow="FORMAT STUDIO" title="RGB & Gradient Generator" description="Translate your server copy into exact legacy, RGB, Bungee, JSON, and MiniMessage syntax."><AccentTag><Sparkles className="mr-1 size-3" /> Live renderer</AccentTag></PageIntro>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.05fr]">
      <div className="space-y-5"><SectionCard title="Compose your text" description="Legacy codes such as &a, &l, and §o are understood in the preview."><div className="space-y-5 p-5 sm:p-6"><div><label className={labelClass}>Minecraft text</label><textarea className={textareaClass} value={text} onChange={(event) => setText(event.target.value)} /></div><div className="grid gap-4 sm:grid-cols-2"><div><label className={labelClass}>Start color</label><div className="flex gap-2"><input type="color" value={start} onChange={(event) => setStart(event.target.value)} className="size-10 rounded-lg border border-white/10 bg-transparent p-1" /><input className={fieldClass} value={start} onChange={(event) => setStart(event.target.value)} /></div></div><div><label className={labelClass}>End color</label><div className="flex gap-2"><input type="color" value={end} onChange={(event) => setEnd(event.target.value)} className="size-10 rounded-lg border border-white/10 bg-transparent p-1" /><input className={fieldClass} value={end} onChange={(event) => setEnd(event.target.value)} /></div></div></div><div className="flex flex-wrap gap-2"><Toggle checked={isGradient} onChange={() => setGradient(!isGradient)} label="Gradient" /><Toggle checked={bold} onChange={() => setBold(!bold)} label="Bold" /><Toggle checked={italic} onChange={() => setItalic(!italic)} label="Italic" /></div></div></SectionCard>
        <SectionCard title="Format payloads" description="Exact copy-ready output for your preferred stack."><div className="space-y-3 p-4">{outputs.map(([label, value]) => <div key={label} className="flex items-center gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] px-3 py-2.5"><span className="w-28 shrink-0 text-[10px] font-bold uppercase tracking-[.1em] text-slate-500">{label}</span><code className="min-w-0 flex-1 truncate text-xs text-slate-300">{value}</code><CopyButton value={value} /></div>)}</div></SectionCard></div>
      <div className="space-y-5"><SectionCard title="Live preview" description="This renderer approximates the Minecraft chat color system."><div className="p-5 sm:p-6"><div className="relative overflow-hidden rounded-xl border border-black/40 bg-[#151922] p-6 shadow-inner"><div className="absolute inset-0 opacity-[.2]" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.05) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.05) 1px, transparent 1px)", backgroundSize: "16px 16px" }} /><div className="relative mb-4 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-600">Chat preview</span><span className="text-[10px] text-slate-600">JAVA EDITION</span></div><div className="relative rounded-lg bg-black/35 px-4 py-6 text-center font-mono text-2xl sm:text-4xl" style={{ ...previewStyle, fontWeight: bold ? 800 : 400, fontStyle: italic ? "italic" : "normal", textShadow: isGradient ? "0 0 18px rgba(85,255,190,.2)" : `0 0 12px ${legacy.color}55` }}>{cleanText}</div><div className="relative mt-4 flex gap-1">{Array.from({ length: 10 }).map((_, index) => <div key={index} className="h-1 flex-1 rounded-full" style={{ background: mixColors(start, end, index / 9) }} />)}</div></div></div></SectionCard>
        <SectionCard title="Birdflop-style multi-stop" description="Add a mid-point for nuanced network branding."><div className="p-5 sm:p-6"><div className="flex items-center gap-2"><input type="color" value={start} onChange={(event) => setStart(event.target.value)} className="size-8 rounded-md border border-white/10 bg-transparent p-0.5" /><div className="h-2 flex-1 rounded-full" style={{ background: `linear-gradient(90deg, ${start}, #b55cff, ${end})` }} /><input type="color" value={end} onChange={(event) => setEnd(event.target.value)} className="size-8 rounded-md border border-white/10 bg-transparent p-0.5" /><button onClick={() => copyText(`<gradient:${start}:#b55cff:${end}>${cleanText}</gradient>`, "Copied to Clipboard!")} className="grid size-8 place-items-center rounded-md border border-white/10 bg-white/[0.04] text-slate-400 hover:text-white"><Plus className="size-4" /></button></div></div></SectionCard></div>
    </div></AppShell>;
}

export function SoundGenerator() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [selected, setSelected] = useState(soundRecords[3]);
  const records = useMemo(() => soundRecords.filter((record) => (category === "All" || record.category === category) && `${record.key} ${record.label}`.toLowerCase().includes(query.toLowerCase())), [query, category]);
  const command = `/playsound minecraft:${selected.key} master @a ~ ~ ~ 1 1`;
  const bukkit = `player.playSound(location, Sound.${selected.key.toUpperCase().replaceAll(".", "_")}, 1f, 1f);`;
  const skript = `play sound "${selected.key}" to player`;
  return <AppShell><PageIntro eyebrow="SOUND INDEX" title="Minecraft Sound Code Helper" description="Search common Java sound keys and instantly copy implementation examples."><AccentTag color="aqua"><BellRing className="mr-1 size-3" /> {soundRecords.length} curated keys</AccentTag></PageIntro>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.08fr]"><SectionCard title="Official sound keys" description="Filter by category or browse the curated starter index."><div className="border-b border-white/[0.07] p-4"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-600" /><input className={`${fieldClass} pl-9`} placeholder="Search sound keys…" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="mt-3 flex flex-wrap gap-2">{["All", "Blocks", "Entities", "Ambient", "Weather", "Items"].map((item) => <button key={item} onClick={() => setCategory(item)} className={classNames("rounded-md px-2.5 py-1 text-xs font-semibold transition", category === item ? "bg-cyan-300/15 text-cyan-200" : "bg-white/[0.035] text-slate-500 hover:text-slate-300")}>{item}</button>)}</div></div><div className="max-h-[455px] overflow-y-auto p-2">{records.map((record) => <button key={record.key} onClick={() => setSelected(record)} className={classNames("flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition", selected.key === record.key ? "bg-cyan-300/[.09]" : "hover:bg-white/[.04]")}><div className={classNames("size-2 rounded-full", selected.key === record.key ? "bg-cyan-300 shadow-[0_0_8px_#55ffff]" : "bg-slate-700")} /><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold text-slate-200">{record.label}</div><div className="truncate font-mono text-[11px] text-slate-500">{record.key}</div></div><span className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-600">{record.category}</span></button>)}{!records.length && <div className="py-12 text-center text-sm text-slate-500">No sound keys match your search.</div>}</div></SectionCard>
      <div className="space-y-5"><SectionCard title="Selected sound" description={selected.label} action={<AccentTag color="aqua">{selected.category}</AccentTag>}><div className="p-5 sm:p-6"><div className="flex items-center justify-between rounded-xl border border-cyan-300/15 bg-cyan-300/[.04] p-4"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-cyan-200/70">Sound key</div><code className="mt-1 block text-sm text-white">{selected.key}</code></div><button onClick={() => copyText(selected.key, "Copied sound key") } className="rounded-lg bg-cyan-300 px-3 py-2 text-xs font-bold text-[#061012] transition hover:bg-cyan-200"><Play className="mr-1.5 inline size-3" /> Test</button></div></div></SectionCard><SectionCard title="Implementation snippets"><div className="space-y-3 p-4"><CodeBlock label="Bukkit API" value={bukkit} /><CodeBlock label="Command" value={command} /><CodeBlock label="Skript" value={skript} /></div></SectionCard></div>
    </div></AppShell>;
}

export function MotdGenerator() {
  const [title, setTitle] = useState("&a&lBlockForge Network");
  const [subtitle, setSubtitle] = useState("&bSurvival &7• &dSkyblock &7• &eMinigames");
  const [players, setPlayers] = useState("42/250");
  const [styles, setStyles] = useState({ bold: true, italic: false, magic: false });
  const cleanTitle = stripLegacy(title);
  const cleanSub = stripLegacy(subtitle);
  const mini = `<gradient:#55ff55:#55ffff>${cleanTitle}</gradient>\n<gray>${cleanSub}</gray>`;
  const config = `motds:\n  main:\n    line1: "${mini.split("\n")[0]}"\n    line2: "${mini.split("\n")[1]}"\n    player-count:\n      online: ${players.split("/")[0] || 42}\n      max: ${players.split("/")[1] || 250}`;
  return <AppShell><PageIntro eyebrow="SERVER LIST PRESENCE" title="Minecraft MOTD Generator" description="Design a compelling multiplayer-list entry with MiniMessage or legacy markup."><AccentTag color="violet"><MonitorPlay className="mr-1 size-3" /> Live server list</AccentTag></PageIntro>
    <div className="grid gap-5 xl:grid-cols-[.95fr_1.05fr]"><div className="space-y-5"><SectionCard title="MOTD content" description="Legacy styles are preserved in the simulator; export as MiniMOTD."><div className="space-y-5 p-5 sm:p-6"><div><label className={labelClass}>First line</label><input className={fieldClass} value={title} onChange={(event) => setTitle(event.target.value)} /></div><div><label className={labelClass}>Second line</label><input className={fieldClass} value={subtitle} onChange={(event) => setSubtitle(event.target.value)} /></div><div><label className={labelClass}>Visible player count</label><input className={fieldClass} value={players} onChange={(event) => setPlayers(event.target.value)} /></div><div><label className={labelClass}>Style toggles</label><div className="flex flex-wrap gap-2"><Toggle checked={styles.bold} onChange={() => setStyles({ ...styles, bold: !styles.bold })} label="Bold" /><Toggle checked={styles.italic} onChange={() => setStyles({ ...styles, italic: !styles.italic })} label="Italic" /><Toggle checked={styles.magic} onChange={() => setStyles({ ...styles, magic: !styles.magic })} label="Magic" /></div></div></div></SectionCard><SectionCard title="Export configurations"><div className="space-y-3 p-4"><CodeBlock label="MiniMOTD config.yml" value={config} /><CodeBlock label="BungeeCord config.yml" value={`motd: '${title}\\n${subtitle}'`} /><CodeBlock label="server.properties" value={`motd=${title}\n${subtitle}`} /></div></SectionCard></div>
      <div><SectionCard title="Multiplayer server list" description="A game-style preview of your first impression."><div className="p-5 sm:p-6"><div className="overflow-hidden rounded-lg border border-[#2c313d] bg-[#161a22] p-1 shadow-[0_15px_30px_rgba(0,0,0,.35)]"><div className="border border-[#333a48] bg-[linear-gradient(90deg,#202632,#1a202a)] p-4"><div className="flex gap-4"><div className="grid size-16 shrink-0 place-items-center rounded-sm border-2 border-[#424958] bg-[linear-gradient(135deg,#55ff55,#0f251c)] shadow-inner"><Boxes className="size-8 text-white/90" /></div><div className="min-w-0 flex-1 font-mono text-sm"><div className="truncate" style={{ color: "#55FF55", fontWeight: styles.bold ? 800 : 400, fontStyle: styles.italic ? "italic" : "normal", textShadow: "0 0 8px rgba(85,255,85,.35)" }}>{cleanTitle}</div><div className="mt-1 truncate text-slate-200">{cleanSub}</div><div className="mt-2 text-xs text-slate-500">{players} players</div></div><div className="flex flex-col items-end justify-between"><Wifi className="size-5 text-emerald-300" /><span className="font-mono text-xs text-slate-300">18ms</span></div></div></div><div className="bg-[#0d1016] px-4 py-2 text-[10px] text-slate-600">MINECRAFT 1.21.4</div></div><p className="mt-4 text-xs leading-5 text-slate-500">Tip: a clear activity summary in line two makes your network legible at a glance.</p></div></SectionCard></div>
    </div></AppShell>;
}

type StatusResult = { online?: boolean; ip?: string; port?: number; players?: { online?: number; max?: number; list?: string[] }; version?: string; motd?: { clean?: string[]; html?: string[] }; icon?: string; hostname?: string; debug?: { ping?: boolean } };
export function ServerStatus() {
  const [domain, setDomain] = useState("mc.hypixel.net");
  const [status, setStatus] = useState<StatusResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const check = async () => { const host = domain.trim().replace(/^https?:\/\//, "").replace(/\/$/, ""); if (!host) return; setLoading(true); setError(""); try { const response = await fetch(`https://api.mcsrvstat.us/2/${encodeURIComponent(host)}`); if (!response.ok) throw new Error("Status endpoint was unavailable."); const data = (await response.json()) as StatusResult; setStatus(data); if (!data.online) setError("This address did not report as online. It may be offline or block status queries."); } catch { setError("Unable to contact the public status endpoint. Check the address and try again."); setStatus(null); } finally { setLoading(false); } };
  const motd = status?.motd?.clean?.join(" ") || "No MOTD was returned.";
  return <AppShell><PageIntro eyebrow="LIVE DIAGNOSTICS" title="Real-Time Server Status" description="Query a public Java server using the mcsrvstat.us response API."><AccentTag><Activity className="mr-1 size-3" /> Public endpoint</AccentTag></PageIntro>
    <SectionCard title="Target address" description="Enter a domain or IP—port numbers are handled by the remote status service."><div className="flex flex-col gap-3 p-5 sm:flex-row sm:p-6"><div className="relative flex-1"><Server className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-600" /><input className={`${fieldClass} pl-9`} value={domain} onChange={(event) => setDomain(event.target.value)} onKeyDown={(event) => event.key === "Enter" && check()} placeholder="mc.example.net" /></div><button onClick={check} disabled={loading} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-emerald-300 px-4 text-sm font-bold text-[#07100e] transition hover:bg-emerald-200 disabled:cursor-wait disabled:opacity-70 active:scale-[.97]">{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Activity className="size-4" />}{loading ? "Checking…" : "Check status"}</button></div></SectionCard>
    {error && <div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.06] px-4 py-3 text-sm text-amber-100/80">{error}</div>}
    {!status && !loading && !error && <div className="mt-5 rounded-2xl border border-dashed border-white/10 py-16 text-center"><Server className="mx-auto size-8 text-slate-700" /><p className="mt-3 text-sm font-semibold text-slate-400">No status query yet</p><p className="mt-1 text-xs text-slate-600">Use the address above to inspect a server response.</p></div>}
    {status && <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><SectionCard title="Server response" description={status.hostname || domain} action={<span className={classNames("inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em]", status.online ? "border-emerald-300/20 bg-emerald-300/10 text-emerald-200" : "border-red-300/20 bg-red-300/10 text-red-200")}><span className={classNames("size-1.5 rounded-full", status.online ? "bg-emerald-300" : "bg-red-300")} />{status.online ? "Online" : "Offline"}</span>}><div className="grid gap-px bg-white/[.06] sm:grid-cols-2"><Metric icon={Users} label="Players" value={`${status.players?.online ?? 0} / ${status.players?.max ?? 0}`} /><Metric icon={Gauge} label="Query response" value={status.debug?.ping ? "Reachable" : "No ping"} /><Metric icon={FileCode2} label="Version" value={status.version || "Unknown"} /><Metric icon={Server} label="Address" value={`${status.ip || domain}${status.port ? `:${status.port}` : ""}`} /></div><div className="p-5"><div className={labelClass}>Formatted MOTD</div><div className="rounded-lg border border-white/[.07] bg-black/20 p-4 font-mono text-sm text-slate-200">{motd}</div></div></SectionCard><div className="space-y-5"><SectionCard title="Player sample" description="Visible player names returned by the server."><div className="p-5">{status.players?.list?.length ? <div className="flex flex-wrap gap-2">{status.players.list.slice(0, 14).map((player) => <span key={player} className="rounded-md border border-white/[.07] bg-white/[.035] px-2 py-1 font-mono text-xs text-slate-300">{player}</span>)}</div> : <p className="text-sm text-slate-500">The server did not expose a player sample.</p>}</div></SectionCard><SectionCard title="Raw destination"><div className="p-4"><CodeBlock value={`GET https://api.mcsrvstat.us/2/${domain}`} /></div></SectionCard></div></div>}
  </AppShell>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="bg-[#10141c] p-5"><Icon className="size-4 text-emerald-300" /><div className="mt-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-600">{label}</div><div className="mt-1 truncate text-sm font-bold text-slate-200" title={value}>{value}</div></div>; }

const tabTemplates = {
  Minimalist: { header: "&a&lBlockForge &7| &fWelcome, %player_name%", footer: "&7Online: &a%server_online%" },
  "RPG Network": { header: "&6✦ &e&lKINGDOMS &6✦\n&7Welcome back, &f%player_name%", footer: "&7Coins: &6%vault_eco_balance% &8• &7Players: &a%server_online%" },
  "Competitive PvP": { header: "&c&lARENA &8// &f%player_name%", footer: "&7Ranked Queue &8• &a%server_online% online" },
  "Animated Style": { header: "&b&l✦ BLOCKFORGE ✦\n&7Network Status: &aONLINE", footer: "&7Store: &bstore.blockforge.dev &8• &f%player_name%" },
};
export function TablistGenerator() {
  const [template, setTemplate] = useState<keyof typeof tabTemplates>("Minimalist");
  const [header, setHeader] = useState(tabTemplates.Minimalist.header);
  const [footer, setFooter] = useState(tabTemplates.Minimalist.footer);
  const setPreset = (value: keyof typeof tabTemplates) => { setTemplate(value); setHeader(tabTemplates[value].header); setFooter(tabTemplates[value].footer); };
  const yaml = `header-footer:\n  enabled: true\n  header:\n${header.split("\n").map((line) => `    - '${line}'`).join("\n")}\n  footer:\n${footer.split("\n").map((line) => `    - '${line}'`).join("\n")}`;
  return <AppShell><PageIntro eyebrow="PLUGIN CONFIG" title="Tablist Config Generator" description="Draft visual network identity for TAB by NEZNAMY or BungeeTabListPlus."><AccentTag color="aqua"><ListIcon className="mr-1 size-3" /> PlaceholderAPI ready</AccentTag></PageIntro>
    <div className="grid gap-5 xl:grid-cols-[.95fr_1.05fr]"><div className="space-y-5"><SectionCard title="Choose a starting point" description="A preset replaces both editor fields."><div className="p-5 sm:p-6"><label className={labelClass}>Starter template</label><div className="relative"><select className={selectClass} value={template} onChange={(event) => setPreset(event.target.value as keyof typeof tabTemplates)}>{Object.keys(tabTemplates).map((name) => <option key={name} value={name}>{name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /></div></div></SectionCard><SectionCard title="Header and footer" description="Use & color codes and common PlaceholderAPI tokens."><div className="space-y-5 p-5 sm:p-6"><div><label className={labelClass}>Header</label><textarea className={textareaClass} value={header} onChange={(event) => setHeader(event.target.value)} /></div><div><label className={labelClass}>Footer</label><textarea className={textareaClass} value={footer} onChange={(event) => setFooter(event.target.value)} /></div><div className="flex flex-wrap gap-2">{["%player_name%", "%server_online%", "%vault_eco_balance%"].map((token) => <button key={token} onClick={() => setFooter(`${footer}${footer ? " " : ""}${token}`)} className="rounded-md border border-cyan-300/15 bg-cyan-300/[.06] px-2 py-1 font-mono text-[10px] text-cyan-200 transition hover:bg-cyan-300/10">{token}</button>)}</div></div></SectionCard></div><div className="space-y-5"><SectionCard title="In-game tablist preview" description="Token values are illustrated with sample player data."><div className="p-5 sm:p-6"><div className="rounded-xl border border-[#303847] bg-[#141922] p-5 text-center shadow-inner"><div className="whitespace-pre-line font-mono text-sm leading-6 text-emerald-300">{stripLegacy(header).replaceAll("%player_name%", "AetherAdmin").replaceAll("%server_online%", "128")}</div><div className="my-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{["AetherAdmin", "BuilderBee", "CreeperKite", "NetherScout", "PixelGrove", "SkyMiner"].map((name) => <div key={name} className="rounded bg-black/25 px-2 py-1.5 text-left font-mono text-xs text-slate-300"><span className="mr-1 text-emerald-300">●</span>{name}</div>)}</div><div className="whitespace-pre-line font-mono text-xs leading-5 text-slate-400">{stripLegacy(footer).replaceAll("%player_name%", "AetherAdmin").replaceAll("%server_online%", "128").replaceAll("%vault_eco_balance%", "2,450")}</div></div></div></SectionCard><SectionCard title="Plugin export"><div className="space-y-3 p-4"><CodeBlock label="TAB config.yml" value={yaml} /><CodeBlock label="BungeeTabListPlus config.yml" value={`header:\n${header.split("\n").map((line) => `- '${line}'`).join("\n")}\nfooter:\n${footer.split("\n").map((line) => `- '${line}'`).join("\n")}`} /></div></SectionCard></div></div></AppShell>;
}

const optimizerProfiles = {
  "Survival (Low Hardware)": { view: 6, simulation: 4, mobs: 35, merge: 3.5, activation: 16 },
  "Survival (50+ Players)": { view: 8, simulation: 5, mobs: 50, merge: 2.5, activation: 24 },
  Anarchy: { view: 10, simulation: 6, mobs: 70, merge: 2, activation: 32 },
  Skyblock: { view: 6, simulation: 4, mobs: 25, merge: 4, activation: 16 },
  Minigames: { view: 7, simulation: 4, mobs: 35, merge: 3, activation: 20 },
};
export function ServerOptimizer() {
  type Settings = typeof optimizerProfiles["Survival (Low Hardware)"];
  const [profile, setProfile] = useState<keyof typeof optimizerProfiles>("Survival (Low Hardware)");
  const [settings, setSettings] = useState<Settings>(optimizerProfiles["Survival (Low Hardware)"]);
  const changeProfile = (value: keyof typeof optimizerProfiles) => { setProfile(value); setSettings(optimizerProfiles[value]); };
  const config = { "server.properties": `view-distance=${settings.view}\nsimulation-distance=${settings.simulation}\nmax-players=100`, "bukkit.yml": `spawn-limits:\n  monsters: ${settings.mobs}\n  animals: ${Math.round(settings.mobs / 7)}\n  water-animals: 3`, "spigot.yml": `world-settings:\n  default:\n    merge-radius:\n      item: ${settings.merge}\n      exp: ${settings.merge}\n    entity-activation-range:\n      animals: ${settings.activation}\n      monsters: ${settings.activation + 8}`, "paper.yml": `chunk-loading-basic:\n  player-max-concurrent-loads: ${settings.view > 8 ? 12 : 8}\nentities:\n  spawning:\n    per-player-mob-spawns: true`, "purpur.yml": `settings:\n  lagging-threshold: 19.0\n  use-alternate-keepalive: true` };
  const [activeFile, setActiveFile] = useState<keyof typeof config>("server.properties");
  const sliders: Array<{ key: keyof Settings; label: string; description: string; min: number; max: number; step: number }> = [{ key: "view", label: "View distance", description: "Chunks sent to each client. Higher values increase memory and chunk-generation pressure.", min: 3, max: 16, step: 1 }, { key: "simulation", label: "Simulation distance", description: "The active tick radius. This is a direct CPU and TPS lever.", min: 3, max: 12, step: 1 }, { key: "mobs", label: "Monster spawn limit", description: "Caps hostile entities per world. Lower values stabilize mob-heavy farms.", min: 15, max: 100, step: 5 }, { key: "merge", label: "Item merge radius", description: "Combines nearby drops to reduce entity count and tick work.", min: 0.5, max: 6, step: 0.5 }, { key: "activation", label: "Entity activation range", description: "Entities outside this radius sleep, reducing background AI load.", min: 8, max: 48, step: 4 }];
  return <AppShell><PageIntro eyebrow="PERFORMANCE PROFILE" title="Server Optimization Guide" description="Shape a practical Paper/Purpur baseline for your workload and hardware envelope."><AccentTag color="violet"><Cpu className="mr-1 size-3" /> TPS-conscious tuning</AccentTag></PageIntro>
    <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><div className="space-y-5"><SectionCard title="Deployment profile" description="Start with a known workload shape; values remain fully adjustable."><div className="p-5 sm:p-6"><label className={labelClass}>Server profile</label><div className="relative"><select className={selectClass} value={profile} onChange={(event) => changeProfile(event.target.value as keyof typeof optimizerProfiles)}>{Object.keys(optimizerProfiles).map((name) => <option key={name} value={name}>{name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /></div></div></SectionCard><SectionCard title="Key runtime settings" description="Adjust gradually, then observe average MSPT and player experience."><div className="divide-y divide-white/[.06]">{sliders.map((item) => <div key={item.key} className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-bold text-slate-200">{item.label}<span title={item.description}><CircleHelp className="size-3.5 text-slate-600" /></span></div><p className="mt-1 max-w-md text-xs leading-5 text-slate-500">{item.description}</p></div><span className="rounded-md border border-violet-300/15 bg-violet-300/[.07] px-2 py-1 font-mono text-xs font-bold text-violet-200">{settings[item.key]}</span></div><input type="range" min={item.min} max={item.max} step={item.step} value={settings[item.key]} onChange={(event) => setSettings({ ...settings, [item.key]: Number(event.target.value) })} className="mt-4 w-full accent-emerald-300" /></div>)}</div></SectionCard></div><div className="space-y-5"><SectionCard title="Generated files" description="Select a target format, then copy it into your configuration directory."><div className="flex overflow-x-auto border-b border-white/[.07] px-2">{(Object.keys(config) as Array<keyof typeof config>).map((file) => <button key={file} onClick={() => setActiveFile(file)} className={classNames("shrink-0 border-b-2 px-3 py-3 text-xs font-semibold transition", activeFile === file ? "border-emerald-300 text-emerald-200" : "border-transparent text-slate-600 hover:text-slate-300")}>{file}</button>)}</div><div className="p-4"><CodeBlock label={activeFile} value={config[activeFile]} /></div></SectionCard><SectionCard title="Operating note"><div className="p-5"><div className="flex gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-emerald-300/10 text-emerald-300"><Gauge className="size-4" /></div><div><h3 className="text-sm font-bold text-slate-200">Measure before and after</h3><p className="mt-1 text-xs leading-5 text-slate-500">Use spark or timings to establish a baseline. Lower simulation distance first when preserving TPS matters more than distant redstone activity.</p></div></div></div></SectionCard></div></div></AppShell>;
}

type DownloadItem = { name: string; kind: string; description: string; accent: "emerald" | "aqua" | "violet"; href?: string; live?: boolean };
const initialDownloads: DownloadItem[] = [{ name: "Purpur", kind: "Hybrid performance", description: "Paper fork with extensive gameplay and performance controls.", accent: "emerald", href: "https://purpurmc.org/downloads" }, { name: "Paper", kind: "Live official API", description: "High-performance server with broad plugin compatibility.", accent: "aqua", live: true }, { name: "Leaf", kind: "Performance fork", description: "A performance-oriented Paper fork for advanced operators.", accent: "violet", href: "https://github.com/Winds-Studio/Leaf" }, { name: "Folia", kind: "Regionized threading", description: "Paper’s multi-threaded region scheduler experiment.", accent: "emerald", href: "https://papermc.io/software/folia" }, { name: "Fabric", kind: "Mod loader", description: "Lightweight modding ecosystem for server-side mods.", accent: "aqua", href: "https://fabricmc.net/use/server/" }, { name: "Forge", kind: "Mod loader", description: "The established modded-server platform.", accent: "violet", href: "https://files.minecraftforge.net/" }, { name: "Velocity", kind: "Proxy", description: "Modern, highly scalable Minecraft network proxy.", accent: "emerald", href: "https://papermc.io/downloads/velocity" }, { name: "Waterfall", kind: "Proxy", description: "BungeeCord fork for familiar proxy deployments.", accent: "aqua", href: "https://papermc.io/downloads/waterfall" }];
export function DownloadsPage() {
  const [version, setVersion] = useState("1.21.4");
  const [downloads, setDownloads] = useState(initialDownloads);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("Official destinations are ready. Resolve a Paper build for the selected version.");
  const resolvePaper = async () => { setLoading(true); setMessage("Resolving the current Paper build…"); try { const response = await fetch(`https://fill.papermc.io/v3/projects/paper/versions/${version}/builds`); if (!response.ok) throw new Error("Build not found"); const data = await response.json() as Array<{ id: number; channel: string; downloads: Record<string, { url: string }> }>; const latest = data.find((build) => build.channel === "STABLE"); if (!latest?.downloads["server:default"]?.url) throw new Error("No stable build"); const href = latest.downloads["server:default"].url; setDownloads((items) => items.map((item) => item.name === "Paper" ? { ...item, href, kind: `Build #${latest.id} • ${version}` } : item)); setMessage(`Paper build #${latest.id} resolved from the official PaperMC API.`); } catch { setMessage("Could not resolve a Paper build for this version. Try an available release or use the official destination."); } finally { setLoading(false); } };
  const accent = { emerald: "border-emerald-300/20 bg-emerald-300/[.06] text-emerald-200", aqua: "border-cyan-300/20 bg-cyan-300/[.06] text-cyan-200", violet: "border-violet-300/20 bg-violet-300/[.06] text-violet-200" };
  return <AppShell><PageIntro eyebrow="SOFTWARE CHANNELS" title="Minecraft Server Downloads" description="Resolve a current Paper artifact, or jump to trusted upstream software destinations."><AccentTag><CloudDownload className="mr-1 size-3" /> Official sources</AccentTag></PageIntro>
    <SectionCard title="Version resolver" description="Paper build metadata resolves in-browser from PaperMC’s current public downloads API."><div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:p-6"><div className="relative max-w-xs flex-1"><select value={version} onChange={(event) => setVersion(event.target.value)} className={selectClass}>{["1.21.4", "1.21.1", "1.20.6", "1.20.4", "1.19.4", "1.18.2", "1.16.5", "1.12.2", "1.8.8"].map((value) => <option value={value} key={value}>{value}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /></div><button onClick={resolvePaper} disabled={loading} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-emerald-300 px-4 text-sm font-bold text-[#07100e] transition hover:bg-emerald-200 disabled:opacity-70"><RefreshCw className={classNames("size-4", loading && "animate-spin")} />{loading ? "Resolving…" : "Resolve Paper build"}</button><p className="text-xs leading-5 text-slate-500 sm:ml-2">{message}</p></div></SectionCard>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{downloads.map((item) => <article key={item.name} className="group flex flex-col rounded-2xl border border-white/[.08] bg-[#10141c] p-5 transition hover:-translate-y-1 hover:border-white/[.14] hover:bg-[#121822]"><div className="flex items-start justify-between gap-3"><div className={classNames("grid size-10 place-items-center rounded-xl border", accent[item.accent])}><Server className="size-5" /></div><span className={classNames("rounded-md border px-2 py-1 text-[9px] font-bold uppercase tracking-[.11em]", accent[item.accent])}>{item.kind}</span></div><h2 className="mt-5 text-lg font-bold tracking-tight text-white">{item.name}</h2><p className="mt-1.5 flex-1 text-sm leading-5 text-slate-500">{item.description}</p><div className="mt-5">{item.href ? <a href={item.href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-300 transition hover:text-emerald-200">{item.name === "Paper" && item.live ? <Download className="size-3.5" /> : <ExternalLink className="size-3.5" />} {item.name === "Paper" && item.live ? "Download .jar" : "Open source"}</a> : <button onClick={resolvePaper} className="text-xs font-bold text-emerald-300 hover:text-emerald-200">Resolve build <ArrowTiny /></button>}</div></article>)}</div>
    <p className="mt-5 text-xs leading-5 text-slate-600">Build availability changes often. Verify all downloads and release notes in the upstream project before deploying to production.</p>
  </AppShell>;
}

function ArrowTiny() { return <span aria-hidden="true">→</span>; }
function ListIcon({ className }: { className?: string }) { return <SlidersHorizontal className={className} />; }
